// Auto-generated by tooling/scripts/sync-components.mjs. Do not edit manually.
import { BzButton } from '../components/button'
import { BzScroll } from '../components/scroll'

import type { Plugin } from 'vue'

export const defaultComponents: Plugin[] = [BzButton, BzScroll]
