import { readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  componentEntriesPath,
  componentsDir,
  defaultComponentsPath,
  themeIndexPath,
} from '../config/project-paths'

const generatedBanner =
  '// Auto-generated by tooling/scripts/sync-components.ts. Do not edit manually.'

function toPascalCase(kebabName: string): string {
  return kebabName
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('')
}

function toExportName(kebabName: string): string {
  return `Bz${toPascalCase(kebabName)}`
}

function getStyleNamespace(kebabName: string): string {
  return `${kebabName.replace(/-/g, '_')}_style`
}

async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await stat(targetPath)
    return true
  } catch {
    return false
  }
}

async function listComponentNames(): Promise<string[]> {
  const entries = await readdir(componentsDir, { withFileTypes: true })
  const componentNames: string[] = []

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue
    }

    const indexPath = path.join(componentsDir, entry.name, 'index.ts')

    if (await pathExists(indexPath)) {
      componentNames.push(entry.name)
    }
  }

  return componentNames.sort((left, right) => left.localeCompare(right))
}

function buildComponentExports(componentNames: string[]): string {
  const exports = componentNames.map((componentName) => `export * from './${componentName}'`)

  return `${generatedBanner}\n${exports.join('\n')}\n`
}

function buildDefaultComponents(componentNames: string[]): string {
  const imports = componentNames
    .map((componentName) => {
      const exportName = toExportName(componentName)
      return exportName
    })
    .join(', ')

  const componentList = componentNames
    .map((componentName) => toExportName(componentName))
    .join(', ')
  const arrayValue = componentList ? `[${componentList}]` : '[]'

  return `${generatedBanner}
${imports ? `import { ${imports} } from '@bzsh-ui/components'\n\n` : ''}import type { Plugin } from 'vue'

export const defaultComponents: Plugin[] = ${arrayValue}
`
}

function buildThemeIndex(componentNames: string[]): string {
  const uses = componentNames
    .map(
      (componentName) =>
        `@use '../../components/${componentName}/style/index' as ${getStyleNamespace(componentName)};`
    )
    .join('\n')

  return `${generatedBanner}
${uses ? `${uses}\n` : ''}@use './base';
`
}

export async function syncComponentRegistry({
  dryRun = false,
}: {
  dryRun?: boolean
} = {}): Promise<void> {
  const componentNames = await listComponentNames()
  const nextComponentExports = buildComponentExports(componentNames)
  const nextDefaultComponents = buildDefaultComponents(componentNames)
  const nextThemeIndex = buildThemeIndex(componentNames)

  if (dryRun) {
    console.log(`Update: ${path.relative(process.cwd(), componentEntriesPath)}`)
    console.log(`Update: ${path.relative(process.cwd(), defaultComponentsPath)}`)
    console.log(`Update: ${path.relative(process.cwd(), themeIndexPath)}`)
    return
  }

  await writeFile(componentEntriesPath, nextComponentExports, 'utf8')
  await writeFile(defaultComponentsPath, nextDefaultComponents, 'utf8')
  await writeFile(themeIndexPath, nextThemeIndex, 'utf8')
}
