import { readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  componentEntriesPath,
  componentsDir,
  defaultComponentsPath,
  themeIndexPath,
} from '../config/project-paths'

/**
 * 自动生成文件的头部注释
 */
const generatedBanner =
  '// Auto-generated by tooling/scripts/sync-components.ts. Do not edit manually.'

/**
 * 将 kebab-case 字符串转换为 PascalCase
 * @param kebabName kebab-case 格式的字符串
 * @returns PascalCase 格式的字符串
 */
function toPascalCase(kebabName: string): string {
  return kebabName
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('')
}

/**
 * 将 kebab-case 组件名转换为导出名称（添加 Bz 前缀）
 * @param kebabName kebab-case 格式的组件名
 * @returns 导出名称（如 BzButton）
 */
function toExportName(kebabName: string): string {
  return `Bz${toPascalCase(kebabName)}`
}

/**
 * 获取样式命名空间
 * @param kebabName kebab-case 格式的组件名
 * @returns 样式命名空间名称
 */
function getStyleNamespace(kebabName: string): string {
  return `${kebabName.replace(/-/g, '_')}_style`
}

/**
 * 检查路径是否存在
 * @param targetPath 要检查的路径
 * @returns 如果路径存在则返回 true，否则返回 false
 */
async function pathExists(targetPath: string): Promise<boolean> {
  try {
    await stat(targetPath)
    return true
  } catch {
    return false
  }
}

/**
 * 列出所有组件名称
 * 组件目录必须包含 index.ts 才会被视为公开组件
 * @returns 按字母顺序排序的组件名称数组
 */
async function listComponentNames(): Promise<string[]> {
  const entries = await readdir(componentsDir, { withFileTypes: true })
  const componentNames: string[] = []

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue
    }

    const indexPath = path.join(componentsDir, entry.name, 'index.ts')

    // 只有当组件有自己的入口文件时，才被视为公开组件
    if (await pathExists(indexPath)) {
      componentNames.push(entry.name)
    }
  }

  return componentNames.sort((left, right) => left.localeCompare(right))
}

/**
 * 构建组件导出文件内容
 * @param componentNames 组件名称数组
 * @returns 组件导出文件的内容
 */
function buildComponentExports(componentNames: string[]): string {
  const exports = componentNames.map((componentName) => `export * from './${componentName}'`)

  return `${generatedBanner}\n${exports.join('\n')}\n`
}

/**
 * 构建默认组件列表文件内容
 * @param componentNames 组件名称数组
 * @returns 默认组件列表文件的内容
 */
function buildDefaultComponents(componentNames: string[]): string {
  const imports = componentNames
    .map((componentName) => {
      const exportName = toExportName(componentName)
      return exportName
    })
    .join(', ')

  const componentList = componentNames
    .map((componentName) => toExportName(componentName))
    .join(', ')
  const arrayValue = componentList ? `[${componentList}]` : '[]'

  return `${generatedBanner}
${imports ? `import { ${imports} } from '@bzsh-ui/components'\n\n` : ''}import type { Plugin } from 'vue'

export const defaultComponents: Plugin[] = ${arrayValue}
`
}

/**
 * 构建主题索引文件内容
 * @param componentNames 组件名称数组
 * @returns 主题索引文件的内容
 */
function buildThemeIndex(componentNames: string[]): string {
  const uses = componentNames
    .map(
      (componentName) =>
        `@use '../../components/${componentName}/style/index' as ${getStyleNamespace(componentName)};`
    )
    .join('\n')

  return `${generatedBanner}
${uses ? `${uses}\n` : ''}@use './base';
`
}

/**
 * 同步组件注册表
 * 根据组件目录结构自动更新：
 * 1. 组件导出文件
 * 2. 默认组件列表
 * 3. 主题索引文件
 * @param options 选项
 * @param options.dryRun 是否只是模拟运行，不实际写入文件
 */
export async function syncComponentRegistry({
  dryRun = false,
}: {
  dryRun?: boolean
} = {}): Promise<void> {
  // 目录树是真相的来源；所有聚合文件都从它派生而来
  const componentNames = await listComponentNames()
  const nextComponentExports = buildComponentExports(componentNames)
  const nextDefaultComponents = buildDefaultComponents(componentNames)
  const nextThemeIndex = buildThemeIndex(componentNames)

  if (dryRun) {
    console.log(`Update: ${path.relative(process.cwd(), componentEntriesPath)}`)
    console.log(`Update: ${path.relative(process.cwd(), defaultComponentsPath)}`)
    console.log(`Update: ${path.relative(process.cwd(), themeIndexPath)}`)
    return
  }

  await writeFile(componentEntriesPath, nextComponentExports, 'utf8')
  await writeFile(defaultComponentsPath, nextDefaultComponents, 'utf8')
  await writeFile(themeIndexPath, nextThemeIndex, 'utf8')
}
