// Auto-generated by tooling/scripts/sync-components.ts. Do not edit manually.
import { BzButton, BzScroll, BzText } from '@bzsh-ui/components'
import { BzButtonAction } from '@bzsh-ui/modules'

import type { Plugin } from 'vue'

export const defaultComponents: Plugin[] = [BzButton, BzScroll, BzText, BzButtonAction]
