// Auto-generated by tooling/scripts/sync-components.mjs. Do not edit manually.
import { BzButton, BzScroll } from '@bzsh-ui/components'

import type { Plugin } from 'vue'

export const defaultComponents: Plugin[] = [BzButton, BzScroll]
